# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JJE_Waivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YahooKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('consumer_key', models.TextField()),
                ('consumer_secret', models.TextField()),
                ('access_token', models.TextField()),
                ('access_secret_token', models.TextField()),
                ('session_handle', models.TextField()),
                ('user_guid', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='YahooStanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('rank', models.IntegerField()),
                ('stat_point_total', models.FloatField()),
                ('stat_1', models.FloatField()),
                ('stat_2', models.FloatField()),
                ('stat_3', models.FloatField()),
                ('stat_4', models.FloatField()),
                ('stat_5', models.FloatField()),
                ('stat_8', models.FloatField()),
                ('stat_12', models.FloatField()),
                ('stat_31', models.FloatField()),
                ('stat_19', models.FloatField()),
                ('stat_22', models.FloatField()),
                ('stat_23', models.FloatField()),
                ('stat_25', models.FloatField()),
                ('stat_24', models.FloatField()),
                ('stat_26', models.FloatField()),
                ('stat_27', models.FloatField()),
                ('stat_points_1', models.FloatField()),
                ('stat_points_2', models.FloatField()),
                ('stat_points_3', models.FloatField()),
                ('stat_points_4', models.FloatField()),
                ('stat_points_5', models.FloatField()),
                ('stat_points_8', models.FloatField()),
                ('stat_points_12', models.FloatField()),
                ('stat_points_31', models.FloatField()),
                ('stat_points_19', models.FloatField()),
                ('stat_points_22', models.FloatField()),
                ('stat_points_23', models.FloatField()),
                ('stat_points_25', models.FloatField()),
                ('stat_points_24', models.FloatField()),
                ('stat_points_26', models.FloatField()),
                ('stat_points_27', models.FloatField()),
                ('standings_week', models.IntegerField()),
                ('current_standings', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JJE_Waivers.YahooTeam')),
            ],
        ),
    ]
