# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JJE_Standings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YahooKey',
        ),
    ]
