# Generated by Django 2.1.2 on 2018-10-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JJE_Standings', '0002_delete_yahookey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yahoostanding',
            options={'ordering': ['current_standings', 'rank']},
        ),
        migrations.AlterField(
            model_name='yahoostanding',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JJE_Waivers.YahooTeam'),
        ),
    ]
