language: python
python: 3.6
install:
 - pip install -r requirements.txt
 - pip install codeclimate-test-reporter
 - pip install coverage
script:
 - python manage.py test
 - coverage run manage.py test
after_sucess:
  - codeclimate-test-reporter