# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JJE_oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTokens',
            new_name='UserToken',
        ),
    ]
