# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('add_player', models.CharField(max_length=255)),
                ('add_position', models.CharField(max_length=255)),
                ('add_LW', models.BooleanField(default=False)),
                ('add_C', models.BooleanField(default=False)),
                ('add_RW', models.BooleanField(default=False)),
                ('add_D', models.BooleanField(default=False)),
                ('add_G', models.BooleanField(default=False)),
                ('add_Util', models.BooleanField(default=False)),
                ('add_IR', models.BooleanField(default=False)),
                ('drop_player', models.CharField(max_length=255)),
                ('drop_LW', models.BooleanField(default=False)),
                ('drop_C', models.BooleanField(default=False)),
                ('drop_RW', models.BooleanField(default=False)),
                ('drop_D', models.BooleanField(default=False)),
                ('drop_G', models.BooleanField(default=False)),
                ('drop_Util', models.BooleanField(default=False)),
                ('drop_IR', models.BooleanField(default=False)),
                ('over_claim_id', models.IntegerField(default=0)),
                ('overclaimed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='YahooTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('logo_url', models.TextField(blank=True)),
                ('manager_name', models.CharField(blank=True, max_length=200)),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='waiverclaim',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JJE_Waivers.YahooTeam'),
        ),
    ]
