# Generated by Django 2.1.2 on 2018-10-11 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JJE_Waivers', '0002_waiverclaim_claim_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waiverclaim',
            options={'ordering': ['-claim_start']},
        ),
        migrations.AlterField(
            model_name='waiverclaim',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JJE_Waivers.YahooTeam'),
        ),
        migrations.AlterField(
            model_name='yahooteam',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
