# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JJE_Waivers', '0002_auto_20170613_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahooteam',
            name='manager_guid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='yahooteam',
            name='team_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
